In [2]:
import numpy as np

In [3]:
#version
np.__version__

'1.20.3'

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 4. How to find the memory size of any array 
x=np.array([1,2,3,4])
print(x)

x.size

[1 2 3 4]


4

In [9]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info


<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x7fa7aea88760>, toplevel='numpy')>

In [20]:
# 6. Create a null vector of size 10 but the fifth value which is 1


x1=np.array(np.zeros(10))
x1[4]=1

print(x1)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
# 7. Create a vector with values ranging from 10 to 49

x2= np.arange(10,49)
x2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [25]:
# 8. Reverse a vector (first element becomes last)

x3= np.arange(10,49)
x3[: :-1]


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [28]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8


x4=np.arange(0,9)

x4

print(np.reshape(x4,(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

x5=np.array([1,2,0,0,4,0])

np.nonzero(x5)


(array([0, 1, 4]),)

In [33]:
#11 Create a 3x3 identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#. Create a 3x3x3 array with random values 

np.random.random((3,3,3))

array([[[0.07069701, 0.87764156, 0.61893187],
        [0.28547027, 0.57153268, 0.50672179],
        [0.82575621, 0.34632816, 0.03391916]],

       [[0.91548722, 0.45081368, 0.42785103],
        [0.23436096, 0.87175454, 0.87729835],
        [0.48046206, 0.10604601, 0.47676744]],

       [[0.85352963, 0.5946588 , 0.23911355],
        [0.94605503, 0.04079053, 0.72387167],
        [0.22073519, 0.19447084, 0.76464593]]])

In [53]:
#13. Create a 10x10 array with random values and find the minimum and maximum values 

x7= np.random.random((10,10))

print(x7)

print(x7.min())
print(x7.max())



[[0.16391531 0.68510969 0.08355524 0.34940342 0.50748095 0.64793151
  0.71464937 0.36122423 0.16946877 0.53740869]
 [0.00951657 0.95500111 0.40606535 0.36096232 0.82692436 0.19285335
  0.60482028 0.25720757 0.83676832 0.89018533]
 [0.60734896 0.50365812 0.53090203 0.44185645 0.65798759 0.15174235
  0.95787019 0.97159845 0.88496156 0.375052  ]
 [0.25595788 0.16062276 0.19990663 0.90811809 0.72030785 0.86260007
  0.12517803 0.01660334 0.28297301 0.41863889]
 [0.54068062 0.49064876 0.82285862 0.62733632 0.89632198 0.37145706
  0.45170089 0.11965052 0.7553542  0.28368534]
 [0.03421134 0.91270051 0.95432581 0.26896309 0.49619274 0.03864439
  0.18765804 0.36092956 0.04756505 0.35055664]
 [0.83081102 0.49722095 0.63338845 0.67528026 0.94402083 0.23370769
  0.4762209  0.84847478 0.30662659 0.30288932]
 [0.38955386 0.74305751 0.36226083 0.55352497 0.79705828 0.90929925
  0.37203846 0.46616287 0.63782021 0.80214783]
 [0.34338667 0.78871152 0.82168893 0.95193782 0.89163499 0.5145007
  0.08987521 

In [55]:
#14. Create a random vector of size 30 and find the mean value 

x_1=np.random.random(30)

x_mean=np.mean(x_1)

print(x_mean)

0.5025474685251242


In [60]:
#15. Create a 2d array with 1 on the border and 0 inside
x_2=np.ones((2,2))

x_2[1:-1, 1:-1]=0

print(x_2)

[[1. 1.]
 [1. 1.]]


In [62]:
#16. How to add a border (filled with 0's) around an existing array? 

x_3=np.pad(x_2,pad_width=1, mode='constant',constant_values=0)
x_3

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#17. What is the result of the following expression? 

0 * np.nan
 np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

#nan = not a number

In [69]:
print(0 * np.nan)

nan


In [70]:
np.nan == np.nan

False

In [75]:
np.nan - np.nan

nan

In [72]:
np.nan in set([np.nan])

True

In [73]:
0.3 == 3 * 0.1

False

In [102]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x_diag=np.array([1,2,3,4])
print(x_diag)
np.diag(x_diag, k=-1)


[1 2 3 4]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [130]:
## 19. Create a 8x8 matrix and fill it with a checkerboard pattern 
x_checkb=np.ones((8,8))
x_checkb[1::2, ::2]=0
x_checkb[::2, 1::2]=0

print(x_checkb)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [131]:
## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

x_x=np.unravel_index(100,(6,7,8))

x_x

(1, 5, 4)